config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  ActiveAdmin.routes(self)
  resources :foot_objs

  resources :architects

  resources :articles

  resources :arch_objects

  root 'arch_objects#index'

end

app/models/arch_object.rb
class ArchObject < ActiveRecord::Base
  has_many :articles
  has_many :arch_objects_architects
  has_many :arch_objects_styles
  has_many :arch_objects_types
  has_many :architects, through: :arch_objects_architects
  has_many :styles, through: :arch_objects_styles
  has_many :types, through: :arch_objects_types
  belongs_to :user

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  DISTRICTS = %w(Суворовский Малиновский Молдаванка Киевский Приморский)
# Не забути видалити STYLES -  сміття
  STYLES = [
   'барокко',
   'неоготика',
   'готика',
   'рококо',
   'модернизированная эклектика',
   'югендстиль',
   'французское барокко',
   'русско-византийский',
   'ранняя эклектика',
   'конструктивизм',
   'венское барокко',
   'венецианский ренессанс',
   'классицизм',
   'ренессанс',
   'псевдоготика',
   'немецкий ренессанс',
   'кирпичный стиль',
   'рациональный модерн',
   'неоренессанс',
   'модернизированный неоампир',
   'модернизированный неоренессанс',
   'орнаментальный модерн',
   'сталинский ампир',
   'эклектика',
   'неоклассицизм',
   'ретроспективный модерн',
   'модерн'
  ]
  STATUS_TYPES = [
   'Памятник мемориального искусства',
   'Не сохранился',
   'Памятник истории национального значения',
   'Памятник истории местного значения',
   'Памятник истории',
   'Памятник истории и архитектуры национального значения',
   'Памятник архитектуры национального значения',
   'Не определён',
   'Объект фоновой застройки',
   'Памятник архитектуры местного',
   'Памятник истории и архитектуры местного значения'
  ]
  OBJECT_TYPES = [
   'музей',
   'театр',
   'библиотека',
   'остановка',
   'общественное сооружение',
   'церковь',
   'жилой дом',
   'электрическая подстанция',
   'павильон остановки',
   'магазин',
   'жилой флигель',
   'торговые ряды',
   'административное',
   'жилой дом с доходными квартирами',
   'внутридворовой жилой флигель',
   'многоквартирный жилой дом',
   'доходный дом',
   'особняк'
  ]
end

app/models/arch_objects_type.rb
class ArchObjectsType < ActiveRecord::Base
  belongs_to :arch_object
  belongs_to :type
end

app/controllers/arch_objects_controller.rb
class ArchObjectsController < ApplicationController
  load_and_authorize_resource

  # GET /arch_objects
  # GET /arch_objects.json
  def index
  end

  # GET /arch_objects/1
  # GET /arch_objects/1.json
  def show
  end

  # GET /arch_objects/new
  def new

  end

  # GET /arch_objects/1/edit
  def edit
  end

  # POST /arch_objects
  # POST /arch_objects.json
  def create
    @user = current_user
    @arch_object = @user.arch_objects.new(arch_object_params)
    respond_to do |format|
      if @arch_object.save
        format.html { redirect_to arch_objects_url @arch_object.id, notice: 'Arch object was successfully created.' }
        format.json { render :show, status: :created, location: @arch_object }
      else
        format.html { render :new }
        format.json { render json: @arch_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arch_objects/1
  # PATCH/PUT /arch_objects/1.json
  def update
    respond_to do |format|
      if @arch_object.update(arch_object_params)
        format.html { redirect_to @arch_object, notice: 'Arch object was successfully updated.' }
        format.json { render :show, status: :ok, location: @arch_object }
      else
        format.html { render :edit }
        format.json { render json: @arch_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arch_objects/1
  # DELETE /arch_objects/1.json
  def destroy
    @arch_object.destroy
    respond_to do |format|
      format.html { redirect_to arch_objects_url, notice: 'Arch object was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arch_object
      @arch_object = ArchObject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arch_object_params
      params.require(:arch_object).permit(:name, :avatar, :foundation, :status, :user_id)
    end
end

app/helpers/arch_objects_helper.rb
module ArchObjectsHelper
end

app/views/arch_objects/_form.html.erb
<%= form_for @arch_object, :url => arch_objects_path, :html => { :multipart => true } do |f| %>
  <% if @arch_object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@arch_object.errors.count, "error") %> prohibited this arch_object from being saved:</h2>

      <ul>
      <% @arch_object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :foundation %><br>
    <%= f.date_select :foundation %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, ArchObject::STATUS_TYPES %>
  </div>
    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/arch_objects/edit.html.erb
<h1>Editing arch_object</h1>

<%= render 'form' %>

<%= link_to 'Show', @arch_object %> |
<%= link_to 'Back', arch_objects_path %>

app/views/arch_objects/index.html.erb
<h1>Listing arch_objects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Avatar</th>
      <th>Foundation</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arch_objects.each do |arch_object| %>
      <tr>
        <td><%= arch_object.name %></td>
        <td><%= image_tag arch_object.avatar.url(:thumb) %></td>
        <td><%= arch_object.foundation %></td>
        <td><%= arch_object.status %></td>
        <td><%= link_to 'Show', arch_object %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Архитекторы', architects_url%>

app/views/arch_objects/new.html.erb
<h1>New arch_object</h1>
<%= debug @arch_object %>
<%= render 'form' %>

<%= link_to 'Back', arch_objects_path %>

app/views/arch_objects/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @arch_object.name %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= image_tag @arch_object.avatar.url(:medium) %>
</p>

<p>
  <strong>Foundation:</strong>
  <%= @arch_object.foundation %>
</p>

<p>
  <strong>Status:</strong>
  <%= @arch_object.status %>
</p>
<p>Статьи</p>
<% @arch_object.articles.each do |article| %>
    <%=link_to article.title, article%>
    <br>
    <%end%>
<p>-----------------</p>
<p>Архитекторы</p>
<% @arch_object.architects.each do |architect| %>
    <%=link_to architect.get_name, architect%>
    <br>
    <%end%>
<p>-----------------</p>
<p>Стили</p>
<% @arch_object.styles.each do |style| %>
    <%=style.name%>
    <br>
    <%end%>
<p>-----------------</p>
<p>Тип</p>
<% @arch_object.types.each do |type| %>
    <%=type.name%>
    <br>
    <%end%>
<p>-----------------</p>
<%= link_to 'Edit', edit_arch_object_path(@arch_object) %> |
<%= link_to 'Back', arch_objects_path %>
<%= link_to 'new article', new_article_url(:arch_object_id => @arch_object.id)%>