config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  ActiveAdmin.routes(self)
  resources :foot_objs

  resources :architects

  resources :articles

  resources :arch_objects

  root 'arch_objects#index'

end

app/models/architect.rb
class Architect < ActiveRecord::Base
  has_many :arch_objects_architects
  has_many :arch_objects, through: :arch_objects_architects
  belongs_to :user

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def get_name
    "#{self.surname} #{self.name[0]}. #{self.familyname[0]}."
  end
  def get_full_name
    "#{self.surname} #{self.name} #{self.familyname}"
  end
end

app/controllers/architects_controller.rb
class ArchitectsController < ApplicationController
  before_action :set_architect, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /architects
  # GET /architects.json
  def index
    @architects = Architect.all
  end

  # GET /architects/1
  # GET /architects/1.json
  def show
  end

  # GET /architects/new
  def new
    @architect = Architect.new
  end

  # GET /architects/1/edit
  def edit
  end

  # POST /architects
  # POST /architects.json
  def create
    @architect = Architect.new(architect_params)


    respond_to do |format|
      if @architect.save
        format.html { redirect_to @architect, notice: 'Architect was successfully created.' }
        format.json { render :show, status: :created, location: @architect }
      else
        format.html { render :new }
        format.json { render json: @architect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /architects/1
  # PATCH/PUT /architects/1.json
  def update
    respond_to do |format|
      if @architect.update(architect_params)
        format.html { redirect_to @architect, notice: 'Architect was successfully updated.' }
        format.json { render :show, status: :ok, location: @architect }
      else
        format.html { render :edit }
        format.json { render json: @architect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /architects/1
  # DELETE /architects/1.json
  def destroy
    @architect.destroy
    respond_to do |format|
      format.html { redirect_to architects_url, notice: 'Architect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_architect
      @architect = Architect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def architect_params
      params.require(:architect).permit(:name, :surname, :familyname, :avatar, :user_id)
    end
end

app/helpers/architects_helper.rb
module ArchitectsHelper
end

app/views/architects/_form.html.erb
<%= form_for(@architect) do |f| %>
  <% if @architect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@architect.errors.count, "error") %> prohibited this architect from being saved:</h2>

      <ul>
      <% @architect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :familyname %><br>
    <%= f.text_field :familyname %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/architects/edit.html.erb
<h1>Editing architect</h1>

<%= render 'form' %>

<%= link_to 'Show', @architect %> |
<%= link_to 'Back', architects_path %>

app/views/architects/index.html.erb
<h1>Listing architects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Familyname</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @architects.each do |architect| %>
      <tr>
        <td><%= architect.name %></td>
        <td><%= architect.surname %></td>
        <td><%= architect.familyname %></td>
        <td><%= image_tag architect.avatar.url(:thumb) %></td>
        <td><%= link_to 'Show', architect %></td>
        <td><%= link_to 'Edit', edit_architect_path(architect) %></td>
        <td><%= link_to 'Destroy', architect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Architect', new_architect_path %>

app/views/architects/new.html.erb
<h1>New architect</h1>

<%= render 'form' %>

<%= link_to 'Back', architects_path %>

app/views/architects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @architect.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @architect.surname %>
</p>

<p>
  <strong>Familyname:</strong>
  <%= @architect.familyname %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= image_tag @architect.avatar.url(:medium) %>
</p>

<%= link_to 'Edit', edit_architect_path(@architect) %> |
<%= link_to 'Back', architects_path %>