config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  ActiveAdmin.routes(self)
  resources :foot_objs

  resources :architects

  resources :articles

  resources :arch_objects

  root 'arch_objects#index'

end

app/models/foot_obj.rb
class FootObj < ActiveRecord::Base
  belongs_to :article
end

app/controllers/foot_objs_controller.rb
class FootObjsController < ApplicationController
  before_action :set_foot_obj, only: [:show, :edit, :update, :destroy]

  # GET /foot_objs
  # GET /foot_objs.json
  def index
    @foot_objs = FootObj.all
  end

  # GET /foot_objs/1
  # GET /foot_objs/1.json
  def show
  end

  # GET /foot_objs/new
  def new
    @foot_obj = FootObj.new
  end

  # GET /foot_objs/1/edit
  def edit
  end

  # POST /foot_objs
  # POST /foot_objs.json
  def create
    @foot_obj = FootObj.new(foot_obj_params)

    respond_to do |format|
      if @foot_obj.save
        format.html { redirect_to @foot_obj, notice: 'Foot obj was successfully created.' }
        format.json { render :show, status: :created, location: @foot_obj }
      else
        format.html { render :new }
        format.json { render json: @foot_obj.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foot_objs/1
  # PATCH/PUT /foot_objs/1.json
  def update
    respond_to do |format|
      if @foot_obj.update(foot_obj_params)
        format.html { redirect_to @foot_obj, notice: 'Foot obj was successfully updated.' }
        format.json { render :show, status: :ok, location: @foot_obj }
      else
        format.html { render :edit }
        format.json { render json: @foot_obj.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foot_objs/1
  # DELETE /foot_objs/1.json
  def destroy
    @foot_obj.destroy
    respond_to do |format|
      format.html { redirect_to foot_objs_url, notice: 'Foot obj was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foot_obj
      @foot_obj = FootObj.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foot_obj_params
      params.require(:foot_obj).permit(:name, :enable, :body, :picture)
    end
end

app/helpers/foot_objs_helper.rb
module FootObjsHelper
end

app/views/foot_objs/_form.html.erb
<%= form_for(@foot_obj) do |f| %>
  <% if @foot_obj.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foot_obj.errors.count, "error") %> prohibited this foot_obj from being saved:</h2>

      <ul>
      <% @foot_obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :enable %><br>
    <%= f.check_box :enable %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foot_objs/edit.html.erb
<h1>Editing foot_obj</h1>

<%= render 'form' %>

<%= link_to 'Show', @foot_obj %> |
<%= link_to 'Back', foot_objs_path %>

app/views/foot_objs/index.html.erb
<h1>Listing foot_objs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Enable</th>
      <th>Body</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foot_objs.each do |foot_obj| %>
      <tr>
        <td><%= foot_obj.name %></td>
        <td><%= foot_obj.enable %></td>
        <td><%= foot_obj.body %></td>
        <td><%= foot_obj.picture %></td>
        <td><%= link_to 'Show', foot_obj %></td>
        <td><%= link_to 'Edit', edit_foot_obj_path(foot_obj) %></td>
        <td><%= link_to 'Destroy', foot_obj, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foot obj', new_foot_obj_path %>

app/views/foot_objs/new.html.erb
<h1>New foot_obj</h1>

<%= render 'form' %>

<%= link_to 'Back', foot_objs_path %>

app/views/foot_objs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @foot_obj.name %>
</p>

<p>
  <strong>Enable:</strong>
  <%= @foot_obj.enable %>
</p>

<p>
  <strong>Body:</strong>
  <%= @foot_obj.body %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @foot_obj.picture %>
</p>

<%= link_to 'Edit', edit_foot_obj_path(@foot_obj) %> |
<%= link_to 'Back', foot_objs_path %>